### ISSUE TITLE
It is not compiling properly on makecode.microbit.org

### ISSUE THREAD

**Issue by jaswaye** [chevyng/pxt-ucl-junkrobot#1]
Good afternoon! I have been trying to use this code with the BBC: Microbit to run a stepper motor, but it has not been working. We uploaded in to makecode.microbit.org and interacted with the blocks. There is little documentation on line to try to help us resolve issues. It will not compile when we try to use the move forward, turn left, or turn right commands. Any help is appreciated.

~Thanks

**Comment by dailinyang** [comment]
I have the same problem here.
error code:
error: pxt_modules/ucl-junkrobot/main.ts(122,13): error TS9260: variable needs to be defined using 'let' instead of 'var'

Thanks!

**Comment by chevyng** [comment]
Hi, sorry for being missing for so long. 

I changed the for-loop from 'var' to 'let'. 

Believe that should solve the issue. 
Closing this issue for now.
